spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springnews
    username: root
    password: buzhidao96923
  data:
    mongodb:
      uri: mongodb://localhost:27017/springnews
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true